package com.example.margumynas.ui.theme

import androidx.compose.ui.graphics.Color

//Light Scheme
val primaryLight = Color(0xFFA0A8FF)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE0E0FF)
val onPrimaryContainerLight = Color(0xFF0F144B)
val secondaryLight = Color(0xFF7783FF)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBBF0B5)
val onSecondaryContainerLight = Color(0xFF002105)
val tertiaryLight = Color(0xFFDFE2FF)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDFE2FF)
val onTertiaryContainerLight = Color(0xFF020202)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1B1B21)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF777680)
val outlineVariantLight = Color(0xFFC7C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3D3D41)
val inverseOnSurfaceLight = Color(0xFFF2EFF7)
val inversePrimaryLight = Color(0xFFBDC2FF)
val surfaceDimLight = Color(0xFFDBD9E0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F2FA)
val surfaceContainerLight = Color(0xFFEFEDF4)
val surfaceContainerHighLight = Color(0xFFEAE7EF)
val surfaceContainerHighestLight = Color(0xFFE4E1E9)
val completeLight = Color(0xFF20BE58)
val ongoingLight = Color(0xFFCEB361)
val lateLight = Color(0xFFF14848)

//Dark Scheme
val primaryDark = Color(0xFF241D3F)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF3D4279)
val onPrimaryContainerDark = Color(0xFFE0E0FF)
val secondaryDark = Color(0xFF5720C4)
val onSecondaryDark = Color(0xFFFDFDFD)
val secondaryContainerDark = Color(0xFF225025)
val onSecondaryContainerDark = Color(0xFFBBF0B5)
val tertiaryDark = Color(0xFF313260)
val onTertiaryDark = Color(0xFF262B61)
val tertiaryContainerDark = Color(0xFF313260)
val onTertiaryContainerDark = Color(0xFFEEF4FC)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF91909A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFD1D4DA)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF545A92)
val surfaceDimDark = Color(0xFF131318)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF34343A)
val completeDark = Color(0xFF20BE58)
val ongoingDark = Color(0xFFCEB361)
val lateDark = Color(0xFFF14848)





